/* automatically generated from settings-dialog.ui */
#ifdef __SUNPRO_C
#pragma align 4 (settings_dialog_ui)
#endif
#ifdef __GNUC__
static const char settings_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char settings_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\"?><interface><object class=\"GtkDialog\" id=\"sett"
  "ings-dialog\"><property name=\"border_width\">5</property><property nam"
  "e=\"title\" translatable=\"yes\">Settings for XFCE Builder</property><p"
  "roperty name=\"resizable\">False</property><property name=\"modal\">Tru"
  "e</property><property name=\"destroy_with_parent\">True</property><prop"
  "erty name=\"icon_name\">gtk-preferences</property><property name=\"type"
  "_hint\">normal</property><property name=\"has_separator\">False</proper"
  "ty><child internal-child=\"vbox\"><object class=\"GtkVBox\" id=\"dialog"
  "-vbox\"><property name=\"visible\">True</property><property name=\"orie"
  "ntation\">vertical</property><property name=\"spacing\">2</property><ch"
  "ild><object class=\"GtkNotebook\" id=\"notebook\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"show_tabs\">False</property><child><object class=\"GtkHBox\""
  " id=\"hbox\"><property name=\"visible\">True</property><property name=\""
  "border_width\">6</property><child><object class=\"GtkVBox\" id=\"vbox1\""
  "><property name=\"visible\">True</property><property name=\"orientation"
  "\">vertical</property><property name=\"spacing\">6</property><child><ob"
  "ject class=\"GtkFrame\" id=\"frame-interface\"><property name=\"visible"
  "\">True</property><property name=\"label_xalign\">0</property><property"
  " name=\"shadow_type\">none</property><child><object class=\"GtkAlignmen"
  "t\" id=\"alignment-interface\"><property name=\"visible\">True</propert"
  "y><property name=\"top_padding\">6</property><property name=\"left_padd"
  "ing\">12</property><child><object class=\"GtkVBox\" id=\"vbox-interface"
  "\"><property name=\"visible\">True</property><property name=\"orientati"
  "on\">vertical</property><property name=\"spacing\">6</property><child><"
  "object class=\"GtkCheckButton\" id=\"button-show-application-icons\"><p"
  "roperty name=\"label\" translatable=\"yes\">Show application icons</pro"
  "perty><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">True</property><property name=\"receives_default\">False</propert"
  "y><property name=\"draw_indicator\">True</property></object><packing><p"
  "roperty name=\"position\">0</property></packing></child><child><object "
  "class=\"GtkCheckButton\" id=\"button-full-command-line\"><property name"
  "=\"label\" translatable=\"yes\">Show full command lines</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"receives_default\">False</property><property"
  " name=\"draw_indicator\">True</property></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">False</property><p"
  "roperty name=\"position\">1</property></packing></child><child><object "
  "class=\"GtkCheckButton\" id=\"button-more-precision\"><property name=\""
  "label\" translatable=\"yes\">Show values with more precision</property>"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "True</property><property name=\"receives_default\">False</property><pro"
  "perty name=\"draw_indicator\">True</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">False</proper"
  "ty><property name=\"position\">2</property></packing></child><child><ob"
  "ject class=\"GtkCheckButton\" id=\"button-monitor-paint-box\"><property"
  " name=\"label\" translatable=\"yes\">Draw borders around monitors</prop"
  "erty><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"receives_default\">False</property"
  "><property name=\"xalign\">0.49000000953674316</property><property name"
  "=\"draw_indicator\">True</property></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">False</property><proper"
  "ty name=\"position\">3</property></packing></child><child><object class"
  "=\"GtkHBox\" id=\"hbox-toolbar-style\"><property name=\"visible\">True<"
  "/property><property name=\"spacing\">6</property><child><object class=\""
  "GtkLabel\" id=\"label-toolbar-style\"><property name=\"visible\">True</"
  "property><property name=\"label\" translatable=\"yes\">Toolbar style:</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">False</property><property name=\"position\">0</pr"
  "operty></packing></child><child><placeholder/></child></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">Fals"
  "e</property><property name=\"position\">4</property></packing></child><"
  "/object></child></object></child><child type=\"label\"><object class=\""
  "GtkLabel\" id=\"label-interface\"><property name=\"visible\">True</prop"
  "erty><property name=\"label\" translatable=\"yes\">&lt;b&gt;Interface s"
  "tyle&lt;/b&gt;</property><property name=\"use_markup\">True</property><"
  "/object></child></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkFrame\" id=\"f"
  "rame-misc\"><property name=\"visible\">True</property><property name=\""
  "label_xalign\">0</property><property name=\"shadow_type\">none</propert"
  "y><child><object class=\"GtkAlignment\" id=\"alignment-misc\"><property"
  " name=\"visible\">True</property><property name=\"top_padding\">6</prop"
  "erty><property name=\"left_padding\">12</property><child><object class="
  "\"GtkVBox\" id=\"vbox-misc\"><property name=\"visible\">True</property>"
  "<property name=\"orientation\">vertical</property><property name=\"spac"
  "ing\">6</property><child><object class=\"GtkCheckButton\" id=\"button-p"
  "rompt-terminate-task\"><property name=\"label\" translatable=\"yes\">Pr"
  "ompt for terminating tasks</property><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">False</property><property name=\"draw_indicator\">True"
  "</property></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">False</property><property name=\"position\">0</"
  "property></packing></child><child><object class=\"GtkCheckButton\" id=\""
  "button-show-status-icon\"><property name=\"label\" translatable=\"yes\""
  ">Hide into the notification area</property><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><property nam"
  "e=\"receives_default\">False</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">1</property></packing></child></object></child></object></child><child"
  " type=\"label\"><object class=\"GtkLabel\" id=\"label-misc\"><property "
  "name=\"visible\">True</property><property name=\"label\" translatable=\""
  "yes\">&lt;b&gt;Miscellaneous&lt;/b&gt;</property><property name=\"use_m"
  "arkup\">True</property></object></child></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">False</property><p"
  "roperty name=\"position\">1</property></packing></child></object><packi"
  "ng><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkVSeparator\" id=\"vseparator1\"><property name=\"orient"
  "ation\">vertical</property></object><packing><property name=\"expand\">"
  "False</property><property name=\"padding\">6</property><property name=\""
  "position\">1</property></packing></child><child><object class=\"GtkVBox"
  "\" id=\"vbox2\"><property name=\"orientation\">vertical</property><prop"
  "erty name=\"spacing\">6</property><child><object class=\"GtkFrame\" id="
  "\"frame-information\"><property name=\"visible\">True</property><proper"
  "ty name=\"sensitive\">False</property><property name=\"label_xalign\">0"
  "</property><property name=\"shadow_type\">none</property><child><object"
  " class=\"GtkAlignment\" id=\"alignment-information\"><property name=\"v"
  "isible\">True</property><property name=\"top_padding\">6</property><pro"
  "perty name=\"left_padding\">12</property><child><object class=\"GtkVBox"
  "\" id=\"vbox-information\"><property name=\"visible\">True</property><p"
  "roperty name=\"orientation\">vertical</property><property name=\"spacin"
  "g\">6</property><child><object class=\"GtkHBox\" id=\"hbox-refresh-rate"
  "\"><property name=\"visible\">True</property><property name=\"spacing\""
  ">6</property><child><object class=\"GtkLabel\" id=\"label-refresh-rate\""
  "><property name=\"visible\">True</property><property name=\"label\" tra"
  "nslatable=\"yes\">Refresh rate:</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">False</property>"
  "<property name=\"position\">0</property></packing></child><child><objec"
  "t class=\"GtkComboBox\" id=\"combobox-refresh-rate\"><property name=\"v"
  "isible\">True</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">1</property></packing></child></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">False</property><p"
  "roperty name=\"position\">0</property></packing></child><child><object "
  "class=\"GtkLabel\" id=\"label-columns\"><property name=\"visible\">True"
  "</property><property name=\"xalign\">0</property><property name=\"label"
  "\" translatable=\"yes\">Columns:</property></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">False</property"
  "><property name=\"position\">1</property></packing></child><child><obje"
  "ct class=\"GtkAlignment\" id=\"alignment-columns\"><property name=\"vis"
  "ible\">True</property><property name=\"left_padding\">12</property><chi"
  "ld><object class=\"GtkScrolledWindow\" id=\"scrolledwindow-columns\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"hscrollbar_policy\">never</property><prop"
  "erty name=\"vscrollbar_policy\">never</property><property name=\"shadow"
  "_type\">in</property><child><object class=\"GtkTreeView\" id=\"treeview"
  "-columns\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property></object></child></object></child></object><p"
  "acking><property name=\"position\">2</property></packing></child></obje"
  "ct></child></object></child><child type=\"label\"><object class=\"GtkLa"
  "bel\" id=\"label-information\"><property name=\"visible\">True</propert"
  "y><property name=\"label\" translatable=\"yes\">&lt;b&gt;Information&lt"
  ";/b&gt;</property><property name=\"use_markup\">True</property></object"
  "></child></object><packing><property name=\"position\">0</property></pa"
  "cking></child></object><packing><property name=\"position\">2</property"
  "></packing></child></object></child><child type=\"tab\"><object class=\""
  "GtkLabel\" id=\"label\"><property name=\"visible\">True</property><prop"
  "erty name=\"label\" translatable=\"yes\">Settings</property></object><p"
  "acking><property name=\"tab_fill\">False</property></packing></child><c"
  "hild><placeholder/></child><child type=\"tab\"><placeholder/></child><c"
  "hild><placeholder/></child><child type=\"tab\"><placeholder/></child></"
  "object><packing><property name=\"position\">1</property></packing></chi"
  "ld><child internal-child=\"action_area\"><object class=\"GtkHButtonBox\""
  " id=\"dialog-action_area\"><property name=\"visible\">True</property><p"
  "roperty name=\"layout_style\">end</property><child><object class=\"GtkB"
  "utton\" id=\"button-close\"><property name=\"label\">gtk-close</propert"
  "y><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">True</property><pro"
  "perty name=\"use_stock\">True</property></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">False</property><p"
  "roperty name=\"position\">0</property></packing></child></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"pack_type"
  "\">end</property><property name=\"position\">0</property></packing></ch"
  "ild></object></child><action-widgets><action-widget response=\"0\">butt"
  "on-close</action-widget></action-widgets></object></interface>"
};

static const unsigned settings_dialog_ui_length = 11244u;

